In [6]:
import numpy as np
from keras.datasets import imdb

(train_data,train_labels),(test_data,test_labels)=imdb.load_data(num_words=10000)

def vectorize_sequences(sequences,dimension=10000):
    results=np.zeros((len(sequences),dimension))
    for i,sequence in enumerate(sequences):
        results[i,sequence]=1.
    return results

x_train=vectorize_sequences(train_data)
x_test=vectorize_sequences(test_data)

y_train=np.asarray(train_labels).astype('float32')
y_test=np.asarray(test_labels).astype('float32')

from keras import models
from keras import layers

model=models.Sequential()
model.add(layers.Dense(32,activation='relu',input_shape=(10000,)))
model.add(layers.Dense(16,activation='relu'))
model.add(layers.Dense(1,activation='sigmoid'))

x_val=x_train[:10000]
partial_x_train=x_train[10000:]

y_val=y_train[:10000]
partial_y_train=y_train[10000:]

model.compile(optimizer='rmsprop',
             loss='binary_crossentropy',
             metrics=['acc'])

history=model.fit(partial_x_train,
                 partial_y_train,
                 epochs=4,
                 batch_size=512,
                 validation_data=(x_val,y_val))



Train on 15000 samples, validate on 10000 samples
Epoch 1/4
15000/15000 [==============================] - 3s 227us/step - loss: 0.4865 - acc: 0.7894 - val_loss: 0.3457 - val_acc: 0.8803
Epoch 2/4
15000/15000 [==============================] - 3s 180us/step - loss: 0.2794 - acc: 0.9030 - val_loss: 0.2887 - val_acc: 0.8898
Epoch 3/4
15000/15000 [==============================] - 3s 180us/step - loss: 0.1991 - acc: 0.9313 - val_loss: 0.3442 - val_acc: 0.8570
Epoch 4/4
15000/15000 [==============================] - 3s 173us/step - loss: 0.1601 - acc: 0.9457 - val_loss: 0.2920 - val_acc: 0.8828


In [24]:
import numpy as np
res=np.zeros((3,7))
list=[[1,2],[3,4],[5,6]]
for i,val in enumerate(list):
    res[i,val]=val
print(res)

[[0. 1. 2. 0. 0. 0. 0.]
 [0. 0. 0. 3. 4. 0. 0.]
 [0. 0. 0. 0. 0. 5. 6.]]
